### ISSUE TITLE
uni-app ios端禁止页面左右拖动

### ISSUE THREAD

**Issue by linfangxing2018** [linfangxing2018/web#2]
问题: 在ios上，有的页面可以左右拖动，在最外层的scoll-view标签设置了scroll-x="false"没有作用

起因：页面有的模块的宽度超过750rpx

解决方法： 一个一个模块的去排查，找到宽度超过750rpx的模块，添加

``` css
overflow-x: hidden;
```
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;但是这种方法比较麻烦，可以使用下面这种方法

``` html
<template>
    <view class="guohao_index">
        <!-- 如果这一层不是scroll-view标签要换成scroll-view或者添加一层scroll-view标签 -->
        <scroll-view style="height: 100%;" scroll-y="true" >          
             <view>     <!-- 这一层额外标签一定要加，要不没有效果>
             
                 <!-- 内容区域 -->
             </view>
        </scroll-view> 
    </view>
</template>
```
``` css
    .guahao_index {   
        width: 100%;
	height: 100%;
        overflow-x: hidden;
	overflow-y: auto;
    }  
```

使用scroll-view最好在里面额外裹上一层view标签
